Repository nuxt/content, pull requests merged in 2022-05, with the labels that each got.

#1027 docs(wording): improve docs sentences
  docs/content/1.getting-started/1.installation.md
  docs/content/1.getting-started/2.your-first-page.md
  docs/content/2.guide/1.writing-content/1.content-directory.md
  docs/content/2.guide/1.writing-content/2.front-matter.md
  docs/content/2.guide/2.displaying-content/1.fetching.md
  docs/content/2.guide/2.displaying-content/2.rendering.md
  docs/content/2.guide/3.syntax/1.mdc.md
Labels: documentation

#1042 docs(tutorial): fix closing tag on codegroup
  docs/content/1.getting-started/2.your-first-page.md
Labels: documentation

#1026 docs(landing): move back icons to components folder
  docs/components/content/IconCopy.vue
  docs/components/content/IconHeart.vue
  docs/components/content/IconMarkdown.vue
  docs/components/content/IconSearch.vue
  docs/content/1.index.md
Labels: documentation

#797 docs(docs): add l10n and i18n snippet
  docs/content/en/integrations.md
Labels: documentation, v1

#990 fix(theme-docs): Add updatedAt keypath to es-ES.js
  packages/theme-docs/src/i18n/es-ES.js
Labels: v1

#999 fix: invalid default import from property-information
  packages/content/templates/nuxt-content.js
Labels: v1

#1001 fix(theme-docs): Add vi-VN.js for Vietnamese
  packages/theme-docs/src/i18n/vi-VN.js
Labels: v1

#1017 docs(content): add Vue components prop casing caveat
  docs/content/en/writing.md
Labels: v1

#1044 docs(repo): migrate issue templates from v1
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#1055 docs(examples): use app-navigation component
  examples/navigation/fetch-content-navigation/app.vue
Labels: documentation

#1054 docs(navigation): add config section
  docs/content/2.guide/2.displaying/3.navigation.md
Labels: documentation

#1059 docs(front-matter): update front-matter properties
  docs/content/2.guide/1.writing/2.markdown.md
Labels: documentation

#1091 docs(starter): update repo url
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/content/1.getting-started/1.installation.md
Labels: documentation

#1093 docs(examples): where queries
  docs/content/4.examples/4.navigation/2.use-route.md
  examples/navigation/use-route/app.vue
  examples/navigation/use-route/content/about.md
  examples/navigation/use-route/content/blog-post.md
  examples/navigation/use-route/content/index.md
  examples/navigation/use-route/nuxt.config.ts
  examples/navigation/use-route/package.json
  examples/navigation/use-route/pages/[...slug].vue
  examples/navigation/use-route/tsconfig.json
  examples/queries/where/app.vue
  examples/queries/where/content/castle-in-the-sky.yml
  examples/queries/where/content/grave-of-the-fireflies.md
  examples/queries/where/content/kiki.json
  examples/queries/where/content/my-neighbor-totoro.json5
  examples/queries/where/content/only-yesterday.md
  examples/queries/where/content/pom-poko.md
  examples/queries/where/content/porco-rosso.md
  examples/queries/where/content/princess-monoke.md
  examples/queries/where/content/spirited-away.md
  examples/queries/where/content/whisper-of-the-heart.md
  examples/queries/where/yarn.lock
Labels: documentation

#1131 docs(querying): fix example json title
  docs/content/3.guide/2.displaying/2.querying.md
Labels: documentation

#1130 docs(migration): add redirects for v1
  docs/public/_redirects
Labels: documentation
